os: linux
dist: xenial
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
python:
  - 3.6
env:
  - CI = true
install:
  - pip install --user -r requirements.txt
before_script:
  - cookiecutter . --no-input
  - cd example_gem
  - bundle install
script:
  - bundle exec rspec
