os: linux
dist: trusty
language: ruby
cache: bundler
rvm:
  - '2.3.0'
python:
  - '3.6'
install:
  - pip install --user -r requirements.txt
before_script:
  - cookiecutter . --no-input
  - cd example_gem
  - ./script/install.sh
script:
  bundle exec rspec
