name: ci

on:
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*' # don't run ci on tags, should already have run on commit tag points to.
    paths-ignore:
      - README.md # don't run for readme changes.
  pull_request:
    branches:
      - 'dependabot*'
  schedule:
    - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install python packages
        run: |
          poetry install --user -r requirements.txt
      - name: Generate package using cookiecutter
        run: |
          cookiecutter . --overwrite-if-exists --no-input
      - name: Install gems (in cookiecutter dir)
        working-directory: example_gem
        run: |
          bundle install
      - name: Run tests (in cookiecutter dir)
        working-directory: example_gem
        run: |
          bundle exec rspec
